name: Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn build 